### ISSUE TITLE
Clicking on a previously-unused tag on a to-be-published post returns a /getPosts error then crashes the application for all users.

### ISSUE THREAD

**Issue by evanteng** [u8k/schlaugh#5]
Can't really test this one that much because it takes forever for the application to start back up again (not sure if it needs to be manually started back up again; sorry if you do lmao), but it's happened multiple times now. I assume it's because of the recent fix.

**Comment by evanteng** [comment]
Other observation: it could just be literally any tag on a to-be-published post.

**Comment by u8k** [comment]
BEAUTIFUL THANK YOU

You just saved me some large amount of time trying to hunt down what was going on. I have been manually putting it back up, yes!

I'm putting the server back up again now, please don't click on a tag again, hopefully no one else thinks to until I can get a fix out shortly.

THANK YOU

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by evanteng** [comment]
No worries, dude, glad to be of help.

**Comment by u8k** [comment]
Should be good now!

**Comment by evanteng** [comment]
Looks good to me.
